config/routes.rb
Bloccit::Application.routes.draw do

 

  devise_for :users

  resources :topics do
    resources :posts, except: [:index]
  end

  match "about" => 'welcome#about', via: :get

  root to: 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user

    # if a member, they can manage their own posts
    # (or create new ones)
    if user.role? :member
        can :manage, Post, :user_id => user.id
        can :manage, Comment, :user_id => user.id
    end

    # Moderaters can delete any post
    if user.role? :moderator
        can :destroy, Post
        can :destroy, Comment
    end

    # Admins can do anything
    if user.role? :admin 
        can :manage, :all
    end

    can :read, :all 

  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  belongs_to :topic
  attr_accessible :body, :title, :topic

  default_scope order('created_at DESC')

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :name, :public
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar
  has_many :posts
  before_create :set_member
  mount_uploader :avatar, AvatarUploader

  ROLES = %w[member moderator admin]
  def role?(base_role)
    role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
  end

  private

  def set_member
    self.role = 'member'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])  
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize! :create, Post, message: "You need to be a member to create a new post."
  end

  def create
      @topic = Topic.find(params[:topic_id])
      @post = current_user.posts.build(params[:post])
      @post.topic = @topic

      authorize! :create, @post, message: "You need to be signed up to do that."
      if @post.save
        flash[:notice] = "Post was saved."
        redirect_to [@topic,@post]
      else
        flash[:error] = "There was an error saving that post. Please try again."
        render :new
      end
    end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :edit, @post, message: "You need to own the post to edit it."
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :update, @post, message: "You need to own the post to edit it."
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was updated."
      redirect_to [@topic,@post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.paginate(page: params[:page], per_page: 10)
  end

  def new
    @topic = Topic.new
    authorize! :create, @topic, message: "You need to be an admin to do that."
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to be an admin to do that."
  end

  def create
    @topic = Topic.new(params[:topic])
    authorize! :create, @topic, message: "You need to be an admin to do that."
    if @topic.save
      flash[:notice] = "Topic was saved."
      redirect_to @topic
    else
      flash[:error] = "Error creating topic, please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to own the topic to update it."
    if @topic.update_attributes(params[:id])
      redirect_to @topic
    else
      flash[:error] = "Error saving topic, please try again."
      render :edit
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end
  def will_paginate(collection_or_options = nil, options = {})
  if collection_or_options.is_a? Hash
    options, collection_or_options = collection_or_options, nil
  end
  unless options[:renderer]
    options = options.merge :renderer => BootstrapLinkRenderer
  end
  super *[collection_or_options, options].compact
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Bloccit", root_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class ="pull-right user-info">
         <% if current_user %>
          <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
          Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
         <% else %>
           <%= link_to "Sign In", new_user_session_path %> or 
           <%= link_to "Sign Up", new_user_registration_path %>
         <% end %>
       </div>

    </ul>

    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

    <%= yield %>
  </div>

  
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for [topic, post], html: { class: 'form-horizontal' } do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-block">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= control_group_tag(post.errors[:title]) do %>
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, rows: 8 %>
    </div>
    <% end %>
  <%= control_group_tag(post.errors[:body]) do %>
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 8 %>
    </div>
  <% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Offer up a unique viewpoint.</li>
      <li>Don't be hatin.</li>
      <li>Be cool like the Fonz.</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Offer up a unique viewpoint.</li>
      <li>Don't be hatin.</li>
      <li>Be cool like the Fonz.</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= markdown @post.title %></h1>

<div class="row">
  <div class="span8">
    <small>
      <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by
      <%= @post.user.name %>
    </small>
    <p><%= markdown @post.body %></p>
  </div>
  <div class="span4">
    <% if can? :edit, @post %>
      <%= link_to "Edit", edit_topic_post_path(@topic,@post), class: 'btn btn-large btn-block' %>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="span-6">
    <p>Guidelines for new topic:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Check to make sure your topic is unique and new.</li>
      <li>Be descriptive, but not too long-winded.</li>
      <li>Please do not include links in the title.</li>
    </ul>
  </div>
  <div class="span-6">
    <%= form_for @topic, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :name, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :description, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :description, rows: 8 %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public topic
          <% end %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="span8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @topics %>
  </div>
  <div class="span4">
    <% if can? :create, Topic %>
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-large btn-block' %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="span-6">
    <p>Guidelines for new topics:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Check to make sure your topic is unique and new.</li>
      <li>Be descriptive, but not too long-winded.</li>
      <li>Please do not include links in the title.</li>
    </ul>
  </div>
  <div class="span-6">
    <%= form_for @topic, html: { class: 'form-horizontal'} do |f| %>
      <div class="control-group">
          <%= f.label :name, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public topic
          <% end %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if can? :update, @topic %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-primary btn-mini' %>
<% end %>

<div class="row">
  <div class="span8">
    <p class="lead"><%= @topic.description %></p>
    <% @posts.each do |post| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to (markdown post.title), [@topic, post] %>
          </h4>
          <small>
            <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
            submitted <%= time_ago_in_words(post.created_at) %> ago by 
            <%= post.user.name %><br/>
            <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @posts %>
  </div>
  <div class="span4">
    <% if can? :create, Post %>
      <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-large btn-block' %>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Julia Mailander</p>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>Bloccit</h1>
  <p>Bloccit is a resource for sharing links with your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-large' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-large' %> today!
  </p>
</div>

<div class="row">
  <div class="span4">
    <h2>Learn Something New!</h2>
    <p>Ever wonder why everyone is full of fun facts and you're not? Why all your friends know the jokes you tell them? Get with the program - join Bloccit!</p>
  </div>
  <div class="span4">
    <h2>Share Your Knowledge</h2>
    <p>We are giving you this big beautiful soapbox, so don't waste it by spewing filth - we do want to know about that one time your grandma asked what a "twerk" is. That is golden.</p>
  </div>
  <div class="span4">
    <h2>Join the Conversation</h2>
    <p>Get connected with local, national, and international populations to see how small the world truly is. We're here for all kinds, we welcome you to share your opinion.</p>
  </div>
</div>